title: tnelsond
author: Tommy
email: tnelsond@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
 I am a servant of Jesus Christ. I love Jesus and my mission is to make him known and show his love. 
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Tommy Downs
  tagline: A Servant of Jesus Christ 
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  disqus_shortname: tnelsond

  # generate social links in footer
  social_links:
    #youtube: tnelsond
    #github: tnelsond 
    #rss: rss
    #youtube_channel: tnelsond 
    #twitter: thelehhman
    #linkedIn: in/thelehhman
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    #youtube_channel_name: tnelsond
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

  navigation:
    - title: About
      url: "/about"
    - title: Music Resources
      url: "/music"
    - title: Writing
      url: "/writing"
    - title: Join Me
      url: "/join"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md
# - morgan.md

# Build settings
#theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
